### ISSUE TITLE
Initial Specification of CLI Tool

### ISSUE THREAD

**Issue by thomasbiesaart** [ChappIO/devrant#2]
The command line tool will be designed in such a way that it can be started for every command that will be executend and then shut down again.
In other words:

- No background services
- Needs quick startup

To achieve this we will need several components:

- A command line input parser that will parse the user input into usable information
- A task runner that will select the correct runtime implementation based on the user input
- A collection of tasks that can be started by the runner above
- A configuration manager that allows the user to customize the behavior of the tool

# Proposed Usage:

```
rant <action> [options]
```

## Start a browsing session

Clear all caches and fetch the latest batch of rants.

```
rant refresh [options]
```

#### Options:

- `-a`/`--algo` set the sorting mode to algo
- `-r`/`--recent` set the sorting mode to recent (default)
- `-t`/`--top` set the sorting mode to top

## Display a rant

Display the next rant from the cache or fetch more rants if the end of the cache has been reached.

**This will be the default action.**

```
rant show
```

**Comment by Supernerd11** [comment]
Why would clear refresh the local cache of rants?
Shouldn't clear just clear the cache.
Or rename clear to refresh.

**Comment by thomasbiesaart** [comment]
I am thinking of calling it `hello` or `refresh` yea because generally you want to call this when you start reading devRant. It will cause the session to reset back to the top of the rant feed.

**Comment by Supernerd11** [comment]
Is it ok if I write something like this in C?
I've started somewhat, but if you want me to stop, I'll gladly do it.
I can't help with this project as I don't program in Java.

**Comment by thomasbiesaart** [comment]
No problem! I would never claim this idea. I'm just making it because a lot of people are asking for it.

devRant's community has a huge amount of linux users so maybe they will even prefer a c implementation.

**Comment by Supernerd11** [comment]
Thanks, I'll help out all I can here though.

**Comment by thomasbiesaart** [comment]
Sure, Thanks :)
